apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: demo
spec:
  limits:
    resources:
      cpu: 100
  requirements:
    - key: kubernetes.io/arch
      operator: In
      values: ["amd64"]
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: karpenter.k8s.aws/instance-category
      operator: In
      values: ["c", "m", "r"]
  providerRef:
    name: demo
  ttlSecondsAfterEmpty: 30
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: demo
spec:
  amiFamily: AL2
  instanceProfile: eks-decc9b78-7c7f-93fd-cc3a-f9c1f4ee4ddc
  subnetSelector:
    karpenter.sh/discovery: pablo-karpenter-demo
  securityGroupSelector:
    karpenter.sh/discovery: pablo-karpenter-demo
