apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: demo-nodeclass
spec:
  amiFamily: AL2023
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: pablo-karpenter-demo
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: pablo-karpenter-demo
  role: "KarpenterNodeInstanceRole"
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: demo-nodepool
spec:
  template:
    spec:
      nodeClassRef:
        apiVersion: karpenter.k8s.aws/v1
        kind: EC2NodeClass
        name: demo-nodeclass
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["on-demand"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
  limits:
    cpu: "100"
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
