apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  # AMI Family - Amazon Linux 2023 is recommended
  amiFamily: AL2023
  
  # Subnet selection - Karpenter will discover subnets tagged for the cluster  
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: pablo-karpenter-demo
        
  # Security Group selection
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: pablo-karpenter-demo
        
  # Instance profile for nodes (will be created automatically by EKS)
  role: "KarpenterNodeInstanceRole"
  
  # User Data (optional customization)
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh pablo-karpenter-demo
    
  # Instance metadata options  
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
---
apiVersion: karpenter.sh/v1
kind: NodePool  
metadata:
  name: general-compute
spec:
  # Template for nodes
  template:
    spec:
      # Reference to EC2NodeClass
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
        
      # Requirements for instances
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os  
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In  
          values: ["spot", "on-demand"]  # Mix of spot and on-demand
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["c", "m", "r"]  # Compute, Memory, General purpose
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]  # Only newer generation instances
          
      # Node properties  
      expireAfter: 720h  # 30 days
      
      # Taints (optional)
      taints:
        - key: example.com/special-workload
          value: "true"
          effect: NoSchedule
          
  # Resource limits
  limits:
    cpu: 1000    # Max 1000 vCPU across all nodes
    memory: 1000Gi # Max 1000 GB RAM
    
  # Disruption settings
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 1m
    budgets:
    - nodes: "10%"  # Don't disrupt more than 10% of nodes at once
